# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Griffith
email: tmgriffith1991@gmail.com
description: > #
  My name is Tim and I am a Frontend Web Developer. I have built a couple of websites using WordPress and can also build a site from scratch using either node.js or jekyll as a server.
  Web Development is my passion. I am currently looking for a new opportunity to join a development team. If you like my portfolio and want to learn more about me, please shoot me a message through 
  the form at the bottom of the page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  tmgriffith

# Build settings
markdown: kramdown

photos:
  - title: Nine10
    url: "/img/portfolio/nine10.jpg"
